/* generated by UI Editor, (c)2011 Actions */
#ifndef _RECORD_STY_H
#define _RECORD_STY_H

#define  STYLE0                            0x0000
#define  SCENE00                           0x0000
#define  STY_RECORD_BG                     0x1000
#define  STY_RECORD_STATE                  0x1001
#define  STY_RECORD_PROGRESS               0x5000
#define  STY_RECORD_FILENAME               0x2000
#define  STY_RECORD_FMFREQ                 0x2001
#define  STY_RECORD_TIME                   0x4000

#endif //_RECORD_STY_H 
