/* generated by UI Editor, (c)2011 Actions */
#ifndef _CONFIG_RES_H
#define _CONFIG_RES_H

#define  CFG_BACKGROUND                    0x0
#define  CFG_CHARGE_0                      0x1
#define  CFG_CHARGE_1                      0x2
#define  CFG_CHARGE_2                      0x3
#define  CFG_CHARGE_3                      0x4
#define  CFG_CHARGE_4                      0x5
#define  POWER_OFF_1                       0x6
#define  POWER_ON_1                        0x7
#define  POWER_ON_10                       0x8
#define  POWER_ON_11                       0x9
#define  POWER_ON_12                       0xa
#define  POWER_ON_13                       0xb
#define  POWER_ON_2                        0xc
#define  POWER_ON_3                        0xd
#define  POWER_ON_4                        0xe
#define  POWER_ON_5                        0xf
#define  POWER_ON_6                        0x10
#define  POWER_ON_7                        0x11
#define  POWER_ON_8                        0x12
#define  POWER_ON_9                        0x13

#endif //_CONFIG_RES_H 
