/* generated by UI Editor, (c)2011 Actions */
#ifndef _MAINMENU_RES_H
#define _MAINMENU_RES_H

#define  FM1                               0x0
#define  MAINMENU_AUDIBLE                  0x1
#define  MAINMENU_BOTTOM                   0x2
#define  MAINMENU_BOTTOM1                  0x3
#define  MAINMENU_EBOOK                    0x4
#define  MAINMENU_FOLDER                   0x5
#define  MAINMENU_MIDDLE                   0x6
#define  MAINMENU_MUSIC                    0x7
#define  MAINMENU_NOW_PLAYING              0x8
#define  MAINMENU_PHOTOS                   0x9
#define  MAINMENU_RADIO                    0xa
#define  MAINMENU_RECORD                   0xb
#define  MAINMENU_SETTING                  0xc
#define  MAINMENU_TOOLS                    0xd
#define  MAINMENU_VIDEO                    0xe
#define  MAINMENU_VOICE                    0xf
#define  MUSIC1                            0x10
#define  SYSTEM1                           0x11
#define  VOICE1                            0x12
#define  BLUE_S                            0x0
#define  BOOKNUM_S                         0x1
#define  DATE_S                            0x2
#define  EBOOK_S                           0x3
#define  FOLDER_S                          0x4
#define  GRAY_S                            0x5
#define  GREEN_S                           0x6
#define  LASTPLAY_S                        0x7
#define  MOVIENUM_S                        0x8
#define  MUSIC_S                           0x9
#define  NOWPLAYING_S                      0xa
#define  PICTURE_S                         0xb
#define  PICTURENUM_S                      0xc
#define  PINK_S                            0xd
#define  PRESETNUM_S                       0xe
#define  RADIO_S                           0xf
#define  RECORD_S                          0x10
#define  RED_S                             0x11
#define  SETTING_S                         0x12
#define  THEME_S                           0x13
#define  TOOLS_S                           0x14
#define  TOTAL_S                           0x15
#define  TRACK_S                           0x16
#define  TRACKNUM_S                        0x17
#define  USER1_S                           0x18
#define  VIDEO_S                           0x19
#define  VOICE_S                           0x1a

#endif //_MAINMENU_RES_H 
