/* generated by UI Editor, (c)2011 Actions */
#ifndef _UPGRADE_STY_H
#define _UPGRADE_STY_H

#define  STYLE0                            0x0000
#define  SCENE_UPGRADE                     0x0000
#define  UPGRADE_BACKGROUND                0x1000
#define  UPGRADE_PERCENT                   0x2000
#define  UPGRADE_STRING2                   0x2001
#define  UPGRADE_STRING                    0x2002
#define  UPGRADE_PROGRESS                  0x5000

#endif //_UPGRADE_STY_H 
