all:	
	make -C ./../../psp_rel/usermodule/enhanced/make_build
	make -C ./../drv/welcome
	make -C ./../drv/Key
	make -C ./../drv/ui
	make -C ./../drv/lcd_ZD932
	make -C ./../drv/fm/FM_5807E
	make -C ./../ap/common
	make -C ./../ap/ap_manager
	make -C ./../ap/ap_music
	make -C ./../ap/ap_config
	make -C ./../ap/ap_mainmenu
	make -C ./../ap/ap_browser
	make -C ./../ap/ap_picture
	make -C ./../ap/music_engine
	make -C ./../ap/ap_udisk
	make -C ./../ap/ap_video
	make -C ./../ap/ap_ebook
	make -C ./../ap/ap_playlist
	make -C ./../ap/ap_record
	make -C ./../ap/ap_setting
	make -C ./../ap/fm_engine
	make -C ./../ap/ap_tools
	make -C ./../ap/ap_radio
	make -C ./../ap/ap_alarm
	make -C ./../ap/ap_upgrade	
clean:
	make -C ./../../psp_rel/usermodule/enhanced/make_build clean
	make -C ./../drv/welcome clean
	make -C ./../drv/Key clean
	make -C ./../drv/ui clean
	make -C ./../drv/lcd_ZD932 clean
	make -C ./../drv/fm/FM_5807E clean	
	make -C ./../ap/common clean
	make -C ./../ap/ap_manager clean
	make -C ./../ap/ap_music clean
	make -C ./../ap/ap_config clean
	make -C ./../ap/ap_mainmenu clean
	make -C ./../ap/ap_browser clean
	make -C ./../ap/ap_picture clean
	make -C ./../ap/music_engine clean
	make -C ./../ap/ap_udisk clean
	make -C ./../ap/ap_video clean
	make -C ./../ap/ap_ebook clean
	make -C ./../ap/ap_playlist clean
	make -C ./../ap/ap_record clean
	make -C ./../ap/ap_setting clean
	make -C ./../ap/fm_engine clean
	make -C ./../ap/ap_tools clean
	make -C ./../ap/ap_radio clean
	make -C ./../ap/ap_alarm clean
	make -C ./../ap/ap_upgrade clean		

clean_target:	
	make -C ./../ap/common clean_target
	make -C ./../ap/ap_manager clean_target
	make -C ./../ap/ap_music clean_target
	make -C ./../ap/ap_config clean_target
	make -C ./../ap/ap_mainmenu clean_target
	make -C ./../ap/ap_browser clean_target
	make -C ./../ap/ap_picture clean_target
	make -C ./../ap/music_engine clean_target
	make -C ./../ap/ap_udisk clean_target
	make -C ./../ap/ap_video clean_target
	make -C ./../ap/ap_ebook clean_target
	make -C ./../ap/ap_playlist clean_target
	make -C ./../ap/ap_record clean_target
	make -C ./../ap/ap_setting clean_target
	make -C ./../ap/fm_engine clean_target
	make -C ./../ap/ap_tools clean_target
	make -C ./../ap/ap_radio clean_target
	make -C ./../ap/ap_alarm clean_target
	make -C ./../ap/ap_upgrade clean_target	