/* generated by UI Editor, (c)2011 Actions */
#ifndef _BROWSER_STY_H
#define _BROWSER_STY_H

#define  STYLE0                            0x0000
#define  SCENE00                           0x0000

#endif //_BROWSER_STY_H 
