/* generated by UI Editor, (c)2011 Actions */
#ifndef _RADIO_STY_H
#define _RADIO_STY_H

#define  STYLE0                            0x0000
#define  SCENE00                           0x0000
#define  PICBOX_PLAY_BG                    0x1000
#define  PICBOX_VOL                        0x1001
#define  PICBOX_FREQ_BG                    0x1002
#define  TEXTBOX_PRESET_NUM                0x2000
#define  TEXTBOX_NO_PRESET                 0x2001
#define  TEXTBOX_PRESET_INFOR              0x2002
#define  PBAR_BAND                         0x5000
#define  NUMBOX_FREQ                       0x3000
#define  SCENE01                           0x0001
#define  TEXTBOX_TIP_INFOR                 0x2003
#define  SCENE02                           0x0002
#define  PICBOX_SEARCH_BG                  0x1003
#define  PICBOX_SEARCH                     0x1004
#define  TEXTBOX_SEARCH                    0x2004
#define  PBAR_SEARCH                       0x5001

#endif //_RADIO_STY_H 
