all:
	make -C ./../common/applib/
	make -C ./../common/common_func
	make -C ./../common/common_ui
	make -C ./../common/common_misc
	make -C ./../common/data
		
clean:
	make -C ./../common/applib  clean
	make -C ./../common/common_func clean
	make -C ./../common/common_ui clean
	make -C ./../common/common_misc clean
	make -C ./../common/data clean
	
clean_target:
	make -C ./../common/applib  clean_target
	make -C ./../common/common_func clean_target
	make -C ./../common/common_ui clean_target
	make -C ./../common/common_misc clean_target
	make -C ./../common/data clean_target
	