/* generated by UI Editor, (c)2011 Actions */
#ifndef _VIDEO_RES_H
#define _VIDEO_RES_H

#define  P_VIDEO_VOL_BG                    0x0
#define  P_VIDEO_VOL_CUR_TAG               0x1
#define  P_VIDEO_VOL_DOWN_TAG              0x2
#define  P_VIDEO_VOL_FORBIDDEN             0x3
#define  P_VIDEO_VOL_LIMIT                 0x4
#define  P_VIDEO_VOL_UP_TAG                0x5
#define  VIDEO_BAR_DOWN                    0x6
#define  VIDEO_BAR_UP                      0x7
#define  VIDEO_FILENAME_BG                 0x8
#define  VIDEO_NUM0                        0x9
#define  VIDEO_NUM1                        0xa
#define  VIDEO_NUM2                        0xb
#define  VIDEO_NUM3                        0xc
#define  VIDEO_NUM4                        0xd
#define  VIDEO_NUM5                        0xe
#define  VIDEO_NUM6                        0xf
#define  VIDEO_NUM7                        0x10
#define  VIDEO_NUM8                        0x11
#define  VIDEO_NUM9                        0x12
#define  VIDEO_NUMCOLON                    0x13
#define  VIDEO_PRO_BG                      0x14
#define  VIDEO_SPEED_0                     0x15
#define  VIDEO_SPEED_1                     0x16
#define  VIDEO_SPEED_2                     0x17
#define  VIDEO_SPEED_3                     0x18
#define  VIDEO_STATE_FASTBACKWARD          0x19
#define  VIDEO_STATE_FASTFORWARD           0x1a
#define  VIDEO_STATE_PAUSE                 0x1b
#define  VIDEO_STATE_PLAY                  0x1c
#define  S_CARD_MENU                       0x0
#define  S_DELETE_VIDEO                    0x1
#define  S_LASTPLAY_MENU                   0x2
#define  S_NO_VIDEO_FILE                   0x3
#define  S_NOPLAY_MENU                     0x4
#define  S_PLAYING_MENU                    0x5
#define  S_REPEAT_ALL                      0x6
#define  S_REPEAT_MODE                     0x7
#define  S_REPEAT_NORMAL                   0x8
#define  S_REPEAT_ONE                      0x9
#define  STR_NULL                          0xa

#endif //_VIDEO_RES_H 
