/* generated by UI Editor, (c)2011 Actions */
#ifndef _VIDEO_STY_H
#define _VIDEO_STY_H

#define  VIDEO_STYLE                       0x0000
#define  VIDEO_SCENE_PLAY                  0x0000
#define  STY_VIDEO_PLAYICON_PICBOX         0x1000
#define  STY_VIDOE_FULLSCREEN_REGION       0x2000
#define  STY_VIDEO_PROGRESS_REGION         0x2001
#define  STY_VIDEO_VOLUME_REGION           0x2002
#define  STY_VIDEO_FASTFLAG_PICBOX         0x1001
#define  STY_VIDEO_FILENAME_TEXTBOX        0x2003

#endif //_VIDEO_STY_H 
