/* generated by UI Editor, (c)2011 Actions */
#ifndef _PICTURE_STY_H
#define _PICTURE_STY_H

#define  STYLE0                            0x0000
#define  SCENE00                           0x0000
#define  STY_PIC_NUM_NUMBERBOX             0x3000
#define  STY_PIC_FILENAME_TEXTBOX          0x2000
#define  STY_PIC_PREVIEW_NUMBERBOX         0x3001

#endif //_PICTURE_STY_H 
