/* generated by UI Editor, (c)2011 Actions */
#ifndef _TEST_RES_H
#define _TEST_RES_H

#define  TEST_BACKGROUND                   0x0
#define  TEST_COUNT_0                      0x1
#define  TEST_COUNT_1                      0x2
#define  TEST_COUNT_2                      0x3
#define  TEST_COUNT_3                      0x4
#define  TEST_COUNT_4                      0x5
#define  TEST_COUNT_5                      0x6
#define  TEST_COUNT_6                      0x7
#define  TEST_COUNT_7                      0x8
#define  TEST_COUNT_8                      0x9
#define  TEST_COUNT_9                      0xa
#define  TEST_PLAY_STATE_BG                0xb
#define  S_TEST_MENU_1                     0x0
#define  S_TEST_MENU_2                     0x1
#define  S_TEST_MENU_3                     0x2
#define  S_TEST_MENU_HEAD                  0x3
#define  S_TEST_MENU_OFF                   0x4
#define  S_TEST_MENU_ON                    0x5
#define  S_TEST_MENU_ROOT                  0x6
#define  S_TEST_MENU_ROOT_2                0x7
#define  S_TEST_PLAY                       0x8
#define  S_TEST_STOP                       0x9
#define  S_TEST_STR                        0xa

#endif //_TEST_RES_H 
