/* generated by UI Editor, (c)2011 Actions */
#ifndef _TEST_STY_H
#define _TEST_STY_H

#define  STYLE0                            0x0000
#define  SCENE00                           0x0000
#define  TEST_PLAY_BG                      0x1000
#define  TEST_PLAY_COUNT                   0x1001
#define  TEST_PLAY_STR                     0x2000
#define  TEST_PLAY_STATE                   0x2001

#endif //_TEST_STY_H 
