/* generated by UI Editor, (c)2011 Actions */
#ifndef _UDISK_RES_H
#define _UDISK_RES_H

#define  P_UDISK_BATTERY_0                 0x0
#define  P_UDISK_BATTERY_1                 0x1
#define  P_UDISK_BATTERY_2                 0x2
#define  P_UDISK_BATTERY_3                 0x3
#define  P_UDISK_BATTERY_4                 0x4
#define  P_UDISK_BG                        0x5
#define  P_UDISK_MP3                       0x6
#define  P_UDISK_MSC                       0x7
#define  P_UDISK_MTP                       0x8
#define  P_UDISK_POINT_1A                  0x9
#define  P_UDISK_POINT_1INA                0xa
#define  P_UDISK_POINT_2A                  0xb
#define  P_UDISK_POINT_2INA                0xc
#define  P_UDISK_POINT_3A                  0xd
#define  P_UDISK_POINT_3INA                0xe
#define  P_UDISK_POINT_4A                  0xf
#define  P_UDISK_POINT_4INA                0x10
#define  P_UDISK_POINT_5A                  0x11
#define  P_UDISK_POINT_5INA                0x12
#define  UDISK_STATE_STR_BG                0x13
#define  S_UDISK_CHARGING                  0x0
#define  S_UDISK_FULL_CHARGED              0x1
#define  S_UDISK_LINKING                   0x2

#endif //_UDISK_RES_H 
