/* generated by UI Editor, (c)2011 Actions */
#ifndef _UDISK_STY_H
#define _UDISK_STY_H

#define  UDISK_LINK                        0x0000
#define  UDISK_LINKING                     0x0000
#define  UDISK_LINK_BG                     0x1000
#define  UDISK_MP3                         0x1001
#define  UDISK_LINK_TYPE                   0x1002
#define  UDISK_STATE_STR                   0x2000
#define  UDISK_POINT_1                     0x1003
#define  UDISK_POINT_2                     0x1004
#define  UDISK_POINT_3                     0x1005
#define  UDISK_POINT_4                     0x1006
#define  UDISK_POINT_5                     0x1007
#define  UDISK_BATTERY                     0x1008

#endif //_UDISK_STY_H 
