/* generated by UI Editor, (c)2011 Actions */
#ifndef _PLAYLIST_STY_H
#define _PLAYLIST_STY_H

#define  STYLE0                            0x0000
#define  PLAYLIST_LOADING                  0x0000
#define  PLAYLIST_BACKGROUND               0x1000
#define  PLAYLIST_LOAD_CYCLE               0x1001
#define  PLAYLIST_PERCENT                  0x2000
#define  PLAYLIST_STRING                   0x2001
#define  PLAYLIST_PROGRESS                 0x5000

#endif //_PLAYLIST_STY_H 
