/* generated by UI Editor, (c)2011 Actions */
#ifndef _PLAYLIST_RES_H
#define _PLAYLIST_RES_H

#define  P_PLIST_BG                        0x0
#define  P_PLIST_LOADING_0                 0x1
#define  P_PLIST_LOADING_1                 0x2
#define  P_PLIST_LOADING_2                 0x3
#define  P_PLIST_LOADING_3                 0x4
#define  P_PLIST_LOADING_4                 0x5
#define  P_PLIST_LOADING_5                 0x6
#define  P_PLIST_LOADING_6                 0x7
#define  P_PLIST_LOADING_7                 0x8
#define  P_PLIST_PROG_0                    0x9
#define  P_PLIST_PROG_BG                   0xa
#define  PLAYLIST_PERCENT_BG               0xb
#define  PLAYLIST_STRING_BG                0xc
#define  PLAYLIST_PROGRESS_BG              0xd
#define  S_PLIST_C_CREAT_FAIL              0x0
#define  S_PLIST_C_DISK_ERR                0x1
#define  S_PLIST_C_SPACE_ERR               0x2
#define  S_PLIST_COMPLETE                  0x3
#define  S_PLIST_H_CREAT_FAIL              0x4
#define  S_PLIST_H_DISK_ERR                0x5
#define  S_PLIST_H_SPACE_ERR               0x6
#define  S_PLIST_SEARCH                    0x7
#define  S_PLIST_U_CREAT_FAIL              0x8
#define  S_PLIST_U_DISK_ERR                0x9
#define  S_PLIST_U_SPACE_ERR               0xa

#endif //_PLAYLIST_RES_H 
