/* generated by UI Editor, (c)2011 Actions */
#ifndef _BROWSER_RES_H
#define _BROWSER_RES_H

#define  S_BROWSER_DEL                     0x0
#define  S_CARDMENU                        0x1
#define  S_DEL_ALL                         0x2
#define  S_DEL_FAILED                      0x3
#define  S_DEL_RADIO_FILE                  0x4
#define  S_DEL_RECORD_FILE                 0x5
#define  S_LASTPLAY                        0x6
#define  S_NO_RADIO_FILE                   0x7
#define  S_NO_RECORD_FILE                  0x8
#define  S_NOPLAY                          0x9
#define  S_PLAYING                         0xa

#endif //_BROWSER_RES_H 
