/* generated by UI Editor, (c)2011 Actions */
#ifndef _MTPSYNC_STY_H
#define _MTPSYNC_STY_H

#define  STYLE0                            0x0000
#define  MTPSYNC_UPDATE                    0x0000
#define  SYNC_BACKGROUND                   0x1000
#define  SYNC_PRINT_STRING                 0x2000

#endif //_MTPSYNC_STY_H 
