/* generated by UI Editor, (c)2011 Actions */
#ifndef _MTPSYNC_RES_H
#define _MTPSYNC_RES_H

#define  P_MTPSYNC_BG                      0
#define  SYNC_PRINT_STRING_BG              1
#define  S_SYNC_COMPLETE_STR               0
#define  S_SYNC_FAULT_STR                  1
#define  S_SYNC_UPDATE_STR                 2

#endif //_MTPSYNC_RES_H 
