/* generated by UI Editor, (c)2011 Actions */
#ifndef _UPGRADE_RES_H
#define _UPGRADE_RES_H

#define  P_UPGRADE_BG                      0x0
#define  P_UPGRADE_PROG_0                  0x1
#define  P_UPGRADE_PROG_BG                 0x2
#define  UPGRADE_PERCENT_BG                0x3
#define  UPGRADE_PROGRESS_BG               0x4
#define  UPGRADE_STRING2_BG                0x5
#define  UPGRADE_STRING_BG                 0x6
#define  S_UPGRADE_FAILED                  0x0
#define  S_UPGRADE_SUCCEED                 0x1
#define  S_UPGRADE_TIPS                    0x2
#define  S_UPGRADING                       0x3

#endif //_UPGRADE_RES_H 
