/* generated by UI Editor, (c)2011 Actions */
#ifndef _COMMON_STY_H
#define _COMMON_STY_H

#define  STYLE_COMMON                      0x0000
#define  HEADBAR                           0x0000
#define  HEADBAR_ICON                      0x1000
#define  HEADBAR_BATTERY                   0x1001
#define  HEADBAR_CARD                      0x1002
#define  HEADBAR_V                         0x0001
#define  HEADBAR_BG_V                      0x1003
#define  HEADBAR_BATTERY_V                 0x1004
#define  HEADBAR_ICON_V                    0x1005
#define  HEADBAR_CARD_V                    0x1006
#define  SHUTOFF                           0x0002
#define  SHUTOFF_BG                        0x1007
#define  SHUTOFF_TIME                      0x1008
#define  LOW_POWER                         0x0003
#define  FULL_CHARGE_BG                    0x1009
#define  FULL_CHARGE_TEXT                  0x2000
#define  LOW_POWER_BG                      0x100a
#define  LOW_POWER_TEXT                    0x2001
#define  LOCK                              0x0004
#define  LOCK_BG                           0x100b
#define  LOCK_HOLD                         0x100c
#define  LOCK_ANIMATION                    0x100d
#define  SCREEN                            0x0005
#define  DIGIT_CLOCK_BG                    0x100e
#define  ALBUM_ART_BG                      0x100f
#define  DIGIT_CLOCK_TIME_24               0x4000
#define  DIGIT_CLOCK_TIME_12               0x4001
#define  DIGIT_CLOCK_TIME_AMPM             0x1010
#define  DIGIT_CLOCK_DATE                  0x4002
#define  DEMO_MODE_PIC                     0x1011
#define  TEXTREAD                          0x0006
#define  TEXTREAD_BG                       0x1012
#define  DIALOG_MSG                        0x8000
#define  DIALOG_MSG_V                      0x8001
#define  DIALOG_ASK                        0x8002
#define  DIALOG_ASK_V                      0x8003
#define  DIALOG_USB                        0x8004
#define  USB_TIME_CLEAR                    0x1013
#define  USB_TIME_ONE                      0x1014
#define  USB_TIME_TWO                      0x1015
#define  USB_TIME_THREE                    0x1016
#define  USB_TIME_FOUR                     0x1017
#define  USB_TIME_FIVE                     0x1018
#define  DIRLIST                           0x6000
#define  FILELIST                          0x6001
#define  MENULIST                          0x6002
#define  MENULIST_HEAD                     0x6003
#define  MENULIST_TITLE                    0x6004
#define  MENULIST_TITLE2                   0x6005
#define  MENULIST_OPTION                   0x6006
#define  MENULIST_OPTION_TITLE             0x6007
#define  MENULIST_OPTION_V                 0x6008
#define  PARAM_SIMPLE                      0x7000
#define  PARAM_TIME_24                     0x7001
#define  PARAM_TIME_12                     0x7002
#define  PARAM_DATE                        0x7003
#define  SLIDER_SIMPLE                     0x9000
#define  SLIDER_SIMPLE_SYM                 0x9001
#define  SLIDER_SIMPLE_V                   0x9002
#define  SLIDER_NUM                        0x9003
#define  SLIDER_NUM_SYM                    0x9004
#define  SLIDER_VOLUMEBAR                  0x9005
#define  VOLUMEBAR_LIMIT                   0x1019
#define  VOLUMEBAR_SILENT                  0x101a
#define  VOLUMEBAR_SILENT_CLEAR            0x101b
#define  VOLUMEBAR_CURRENT                 0x101c
#define  VOLUMEBAR_CURRENT_CLEAR           0x101d
#define  VOLUMEBAR_RIGHT_ARROW             0x5000
#define  VOLUMEBAR_LEFT_ARROW              0x5001
#define  VOLUMEBAR_SPEAKER                 0x101e
#define  VOLUMEBAR_PARAM                   0x0060
#define  SLIDER_VOLUMEBAR_V                0x9006
#define  VOLUMEBAR_LIMIT_V                 0x101f
#define  VOLUMEBAR_UP_V                    0x1020
#define  VOLUMEBAR_DOWN_V                  0x1021
#define  VOLUMEBAR_SILENT_V                0x1022
#define  VOLUMEBAR_UP_CLEAR_V              0x1023
#define  VOLUMEBAR_DOWN_CLEAR_V            0x1024
#define  VOLUMEBAR_CURRENT_LINE_V          0x1025
#define  VOLUMEBAR_CURRENT_CLEAR_V         0x1026
#define  VOLUMEBAR_SILENT_CLEAR_V          0x1027
#define  VOLUMEBAR_V_PARAM                 0x006c
#define  SLIDER_SETEQ                      0x9007
#define  DELETED                           0x0021
#define  DELETED_BG                        0x1028
#define  DELETED_INFOR                     0x2002
#define  DELETED_ANIM                      0x1029
#define  DELETED_V                         0x0022
#define  DELETED_BG_V                      0x102a
#define  DELETED_INFOR_V                   0x2003
#define  DELETED_ANIM_V                    0x102b

typedef struct volumebar_param
{
    unsigned short slider_length;    /* 滑动条长度 */
    unsigned short slider_direction;    /* 滑动条方向，0表示竖向，1表示横向 */
}volumebar_param;

typedef struct volumebar_v_param
{
    unsigned short slider_length;    /* 滑动条长度 */
    unsigned short slider_direction;    /* 滑动条方向，0表示竖向，1表示横向 */
}volumebar_v_param;

#endif //_COMMON_STY_H 
