/* generated by UI Editor, (c)2011 Actions */
#ifndef _LANG_ID_H
#define _LANG_ID_H

#define  CZECH                             0
#define  GREEK                             1
#define  ENGLISH                           2
#define  DANISH                            3
#define  GERMAN                            4
#define  SPANISH                           5
#define  FRENCH                            6
#define  ITALIAN                           7
#define  HUNGARIAN                         8
#define  DUTCH                             9
#define  NORWEGIAN                         10
#define  POLISH                            11
#define  PORTUGUESE_EUROPEAN               12
#define  PORTUGUESE_BRAZILIAN              13
#define  RUSSIAN                           14
#define  SLOVAK                            15
#define  FINNISH                           16
#define  SWEDISH                           17
#define  TURKISH                           18
#define  CHINESE_SIMPLIFIED                19
#define  CHINESE_TRADITIONAL               20
#define  JAPANESE                          21
#define  KOREAN                            22
#define  HEBREW                            23
#define  ARABIC                            24
#define  THAI                              25
#define  ROMANIAN                          26
#define  INDONESIAN                        27

#endif //_LANG_ID_H 
