/* generated by UI Editor, (c)2011 Actions */
#ifndef _CONFIG_STY_H
#define _CONFIG_STY_H

#define  STYLE0                            0x0000
#define  POWER_ON                          0x0000
#define  STY_POWER_ON                      0x1000
#define  POWER_OFF                         0x0001
#define  STY_POWER_OFF                     0x1001
#define  SCENE_CHARGING                    0x0002
#define  STY_CFG_CHARGING                  0x1002
#define  BACKGROUND                        0x0003
#define  STY_CFG_BACKGROUND                0x1003

#endif //_CONFIG_STY_H 
