/* generated by UI Editor, (c)2011 Actions */
#ifndef _ALARM_STY_H
#define _ALARM_STY_H

#define  STYLE0                            0x0000
#define  SCENE00                           0x0000

#endif //_ALARM_STY_H 
