/* generated by UI Editor, (c)2011 Actions */
#ifndef _ALARM_RES_H
#define _ALARM_RES_H

#define  P_ALARM1                          0x0
#define  P_ALARM2                          0x1
#define  P_ALARM3                          0x2
#define  P_ALARM4                          0x3
#define  P_ALARM5                          0x4
#define  P_ALARM_BG                        0x5
#define  FORMAT_ERROR                      0x0
#define  S_ALARM                           0x1
#define  S_ALARM_OPENFAIL                  0x2
#define  S_ALARM_OPTION                    0x3

#endif //_ALARM_RES_H 
