/* generated by UI Editor, (c)2011 Actions */
#ifndef _EBOOK_STY_H
#define _EBOOK_STY_H

#define  STYLE0                            0x0000
#define  SCENE00                           0x0000
#define  PLAY_SCENE_BACKGD                 0x1000
#define  TEXT_BACKGD                       0x1001
#define  FILE_NAME_BACKGD                  0x1002
#define  AUTO_PLAY_PICBOX                  0x1003
#define  FILE_NAME                         0x2000
#define  TRACK_NUMBER_BOX                  0x3000

#endif //_EBOOK_STY_H 
