/* generated by UI Editor, (c)2011 Actions */
#ifndef _EBOOK_RES_H
#define _EBOOK_RES_H

#define  EBOOKBG_P                         0x0
#define  EBOOK_FILENAME_BG_P               0x1
#define  EBOOK_TEXT_BG_P                   0x2
#define  EBOOK_TEXT_BG_P2                  0x3
#define  NUM0_P                            0x4
#define  NUM1_P                            0x5
#define  NUM2_P                            0x6
#define  NUM3_P                            0x7
#define  NUM4_P                            0x8
#define  NUM5_P                            0x9
#define  NUM6_P                            0xa
#define  NUM7_P                            0xb
#define  NUM8_P                            0xc
#define  NUM9_P                            0xd
#define  NUM_COVER                         0xe
#define  P_AUTO_PLAY                       0xf
#define  P_MANUAL_PLAY                     0x10
#define  SLASH_P                           0x11
#define  TRACK_NUMBER_BOX_BG               0x12
#define  S_ADD_BMK                         0x0
#define  S_ADDBMK                          0x1
#define  S_ADDOPTION                       0x2
#define  S_AUTOPLAY                        0x3
#define  S_BMKSELECT                       0x4
#define  S_DELETE_BMK                      0x5
#define  S_DELETE_TEXT                     0x6
#define  S_DELETEBMK                       0x7
#define  S_DELETEEBK                       0x8
#define  S_DELETEFILE                      0x9
#define  S_DELETEOPTION                    0xa
#define  S_FULLMSG                         0xb
#define  S_LPLAYNOREAD                     0xc
#define  S_LPLAYNOREAD_C                   0xd
#define  S_LPLAYREAD                       0xe
#define  S_LPLAYREAD_C                     0xf
#define  S_MANUPLAY                        0x10
#define  S_NOBMK                           0x11
#define  S_NOPLAYNOREAD                    0x12
#define  S_NOPLAYNOREAD_C                  0x13
#define  S_NOPLAYREAD                      0x14
#define  S_NOPLAYREAD_C                    0x15
#define  S_NOWPLAYNOREAD                   0x16
#define  S_NOWPLAYNOREAD_C                 0x17
#define  S_NOWPLAYREAD                     0x18
#define  S_NOWPLAYREAD_C                   0x19
#define  S_PAGESELECT                      0x1a
#define  S_PLAYSETTING                     0x1b
#define  S_REPLACEOPTION                   0x1c
#define  S_TEXT_NOFOUND                    0x1d

#endif //_EBOOK_RES_H 
