/* generated by UI Editor, (c)2011 Actions */
#ifndef _PICTURE_RES_H
#define _PICTURE_RES_H

#define  PICTURE_DIR                       0x0
#define  PICTURE_FILENAME_BG               0x1
#define  PICTURE_HEAD_NUM_BG               0x2
#define  PICTURE_NO_THUMBNAIL              0x3
#define  H1_NUMPOINT                       0x4
#define  S_BACKLIGHT                       0x0
#define  S_CARD_MENU                       0x1
#define  S_DELETE_PIC                      0x2
#define  S_IS_STOP_MUSIC                   0x3
#define  S_LASTPLAY_NOPREVIEW              0x4
#define  S_LASTPLAY_PREVIEW                0x5
#define  S_NO_PIC_FILE                     0x6
#define  S_NOPLAY_NOPREVIEW                0x7
#define  S_NOPLAY_PREVIEW                  0x8
#define  S_PLAYING_NOPREVIEW               0x9
#define  S_PLAYING_PREVIEW                 0xa
#define  S_PREVIEW                         0xb
#define  S_REPEAT                          0xc
#define  S_SHUFFLE                         0xd
#define  S_SLIDE_SET                       0xe
#define  S_TIME_PER_SLIDE                  0xf
#define  STR_NULL                          0x10

#endif //_PICTURE_RES_H 
