/* generated by UI Editor, (c)2011 Actions */
#ifndef _MUSIC_STY_H
#define _MUSIC_STY_H

#define  STYLE0                            0x0000
#define  MUSIC_PLAY                        0x0000
#define  PLAY_SCENE_BACKGD                 0x1000
#define  LOOP_MODE_PICBOX                  0x1001
#define  ID3_SCROLL_TEXTBOX                0x2000
#define  SHUFFLE_MODE_PICBOX               0x1002
#define  TRACK_NUMBER_BOX                  0x3000
#define  MUSIC_CURTIME_TIMERBOX            0x4000
#define  MUSIC_PLAY_PROGRESSBAR            0x5000
#define  ALBUM_ART_BGPIC                   0x1003
#define  ALBUM_ART_PICBOX                  0x1004
#define  ID3_MUSIC_PICBOX                  0x1005
#define  AB_STATUS_PICBOX                  0x1006
#define  FULLSOUND_MODE_PICBOX             0x1007
#define  EQ_MODE_PICBOX                    0x1008
#define  PLAY_STATUS_PICBOX                0x1009
#define  ALBUM_ART_REGION                  0x2001
#define  AUDIBLE_PLAY                      0x0001
#define  AUDIBLE_SCENE_BACKGD              0x100a
#define  ID3_AUDIBLE_PICBOX                0x100b
#define  AUDIBLE_TIMERBOX                  0x4001
#define  OTHER_SCENE                       0x0002
#define  OTHER_SCENE_BACKGD                0x100c
#define  SHOW_LYRIC_TEXTBOX                0x2002
#define  ALBUM_NAME_TEXTBOX                0x2003

#endif //_MUSIC_STY_H 
