/* generated by UI Editor, (c)2011 Actions */
#ifndef _TOOLS_STY_H
#define _TOOLS_STY_H

#define  STYLE0                            0x0000
#define  TOOLS_CALENDAR                    0x0000
#define  CALENDAR_BG                       0x1000
#define  CAL_WEEK7                         0x2000
#define  CAL_WEEK1                         0x2001
#define  CAL_WEEK2                         0x2002
#define  CAL_WEEK3                         0x2003
#define  CAL_WEEK4                         0x2004
#define  CAL_WEEK5                         0x2005
#define  CAL_WEEK6                         0x2006
#define  CAL_LUNAR_1                       0x2007
#define  CAL_LUNAR_2                       0x2008
#define  CAL_LUNAR_3                       0x2009
#define  CAL_LUNAR_YR                      0x200a
#define  CAL_LUNAR_MN                      0x200b
#define  CAL_LUNAR_M                       0x200c
#define  CAL_LUNAR_DY                      0x200d
#define  CALENDAR_DATA                     0x4000
#define  GREEN_BG                          0x0001
#define  TOOLS_BG                          0x1001
#define  TOOLS_FM                          0x0002
#define  PICBOX_FREQ_BG                    0x1002
#define  PICBOX_FM_ICON                    0x1003
#define  STOPWATCH                         0x0003
#define  STOPWATCH_BG                      0x1004

#endif //_TOOLS_STY_H 
